---
- name: Install git
  hosts: all
  tasks:
  - name: Install git
    yum: name=httpd state=present
- name: Install wget
  hosts: all
  tasks:
  - name: Install wget
    yum: name=httpd state=present
...
