---
- name: Touch and remove
  hosts: all
  tasks:
  - name: Install git
    file: dest=/opt/devopsschool.txt state=touch
- name: Touch and remove
  hosts: all
  tasks:
  - name: Touch and remove
    file: dest=/opt/devopsschool.txt state=absent
...
