---
- name: This sets up an httpd webserver
  hosts: web
  vars:
    myname: "Rajeshkumar"
    package: "httpd"
  tasks:
  - name: Install the httpd apps
    yum: name={{ package }}
  - name: start the httpd service
    service: name={{package}} state=started
  - name: create a empty fle
    file: dest=/opt/test.txt state=touch
  - name: copy a file
    copy: dest=/var/www/html/ src="/home/ec2-user/index.html"
  - debug:
      msg: Myname is {{ myname }}
...
