---
- name: This sets up an httpd webserver
  hosts: web
  vars:
    myname: "Rajeshkumar"
    package: "httpd"
  vars_files:
    - ext.yaml
  vars_prompt:
    - name: "mycompname"
      prompt: "Which company you work for - Enter it here:-"
  tasks:
  - name: Ansible register variable basic example
    shell: "find *.txt"
    args:
      chdir: "/home/ec2-user"
    register: find_output
  - name: Install the httpd apps
    yum: name={{ package }}
  - name: start the httpd service
    service: name={{package}} state=started
  - name: create a empty fle
    file: dest=/opt/test.txt state=touch
  - name: copy a file
    copy: dest=/var/www/html/ src="/home/ec2-user/index.html"
  - debug:
      msg: Myname is {{ myname2 }}
  - debug:
      msg: My filename is {{ find_output }}
...
