---
# tasks file for web
  - name: Install the httpd apps
    yum: name=httpd
    when: ansible_distribution == 'CentOS'
  - name: Template a file to /etc/files.conf
    template:
      src: index.html.j2
      dest: /var/www/html/index2.html
    notify:
    - restart apache
  - name: start the httpd service
    service: name=httpd state=started
  - name: copy a file
    copy: dest=/var/www/html/ src="/home/ec2-user/index.html"
  - name: Template a file to /etc/httpd.conf
    template:
      src: httpd.j2
      dest: /etc/httpd/conf/httpd.conf
    notify:
    - restart apache
  - name: Ansible register variable basic example
    shell: "find *.txt >> var.yaml"
    args:
      chdir: "/home/vagrant"
    register: find_output
  - name: create a user group
    group:
      name: deloitte
      state: present
  - name: create a user group
    user:
      name: deploy
      group: deloitte
      shell: /bin/bash
- name: install basic packages
  yum:  name={{ item }} state=present 
  with_items:
    - ntp
    - vim
    - git
